### ISSUE TITLE
Webpack error in 2.5.4

### ISSUE THREAD

**Issue by horaceleung** [react-ga/react-ga#313]
We are getting the below error when running the latest 2.5.4 release:

node_modules/react-ga/dist/react-ga.js:10
})(window, function(__WEBPACK_EXTERNAL_MODULE__0__, __WEBPACK_EXTERNAL_MODULE__1__) {
   ^

ReferenceError: window is not defined
    at Object.<anonymous> (/Users/xxx/node_modules/react-ga/dist/react-ga.js:10:4)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.react-ga (/Users/xxx-static/bundle.js:78678:18)
    at __webpack_require__ (/Users/xxx-static/bundle.js:638:30)

**Comment by anajavi** [comment]
I can't reproduce the error using webpack 4.

What version of webpack are you using? Can you share the babel config too, as webpack should use the ESM build when available.

**Comment by anajavi** [comment]
@horaceleung Can you try out the PR #314?

**Comment by DesignMonkey** [comment]
get the same error. I just deployed with the version as "^2.5.3" in package.json. And now I get the error. Seems like it try to execute the react-ga just by importing the package with SSR on. I have a if(window) around my ReactGA.init function.

**Comment by horaceleung** [comment]
I tried the 2.5.5-0 release and it has fixed my issue, thanks!
