### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by yrik** [react-ga/react-ga#67]
Got an error while tried to render component on server side.

```

/Users/yrik/Desktop/django_projects/prettystay/node_modules/react-ga/src/index.js:55
    })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');
       ^

ReferenceError: window is not defined
    at Object.ReactGA.initialize (/Users/yrik/Desktop/django_projects/prettystay/node_modules/react-ga/src/index.js:55:8)
    at Object.<anonymous> (PlaceDetailItem.jsx:8:4)
    at Module._compile (module.js:425:26)
    at loader (/Users/yrik/Desktop/django_projects/prettystay/node_modules/babel-register/lib/node.js:126:5)
    at Object.require.extensions.(anonymous function) [as .jsx] (/Users/yrik/Desktop/django_projects/prettystay/node_modules/babel-register/lib/node.js:136:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (PlaceDetail.jsx:7:1)

```

**Comment by vincentaudebert** [comment]
+1

**Comment by vincentaudebert** [comment]
Haven't had time to look into yet but anyone facing the same issue and found a temp fix?

**Comment by aq1018** [comment]
@yrik node run time doesn't have `window` object. Maybe it shouldn't be rendered on server side?

**Comment by vincentaudebert** [comment]
yeah +1 on @aq1018's comment. I just disabled the analytics on the server side rendering and it worked better.

**Comment by yangshun** [comment]
Yes as @aq1018 there's no `window` object in the server. While you can use the other methods in your server-side rendered component, the call to `initialize` should be made on the client side.

**Comment by cbrwizard** [comment]
What if I want to emit events on the server side?
