### ISSUE TITLE
Add testing information

### ISSUE THREAD

**Issue by otajor** [react-ga/react-ga#96]
React GA has been causing problems in our unit tests - any file that imports ReactGA throws an error when we try to test it, because React GA requires a window object with a script tag. 

It is not obvious how to fix this and usual solutions of simply importing `jsdom` or similar don't fix it. We are now following a similar approach to the tests in this repository of having setup and teardown functions that simulate the window with the correct configuration for React GA

This seems like overkill when we're not even testing React GA, but just testing functions that use React GA.

Do you have any tips or workarounds for this situation? It would be really useful to include some info about this in the readme

**Comment by jmacadam** [comment]
👍

**Comment by sergei-zelinsky** [comment]
Does anyone found a way to test application that using `react-ga`. I'm currently using `jest` for testing my application.

Thanks!

**Comment by bflannery** [comment]
Also having testing issues. running react, redux, mocha, webpack and below is the error I receive when trying to run a unit test. I've set up react-ga with react-router 4 and everything is tracking properly on my Google Analytics account. 

`> to-portal-react@1.0.0 test /Users/brianflannery/Development/react-portal
> NODE_ENV=test mocha --recursive test/specs/

JQMIGRATE: Migrate is installed, version 3.0.0
Warning: ReactTestUtils has been moved to react-dom/test-utils. Update references to remove this warning.
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.
Warning: AutosizeInput: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.
/Users/brianflannery/Development/react-portal/node_modules/react-ga/src/index.js:54
      m.parentNode.insertBefore(a, m);
       ^

TypeError: Cannot read property 'parentNode' of undefined
    at /Users/brianflannery/Development/react-portal/node_modules/react-ga/src/index.js:54:8
    at Object.initialize (/Users/brianflannery/Development/react-portal/node_modules/react-ga/src/index.js:55:7)
    at Object.<anonymous> (/Users/brianflannery/Development/react-portal/src/app.js:18:9)
    at Module._compile (module.js:569:30)
    at loader (/Users/brianflannery/Development/react-portal/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/brianflannery/Development/react-portal/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/brianflannery/Development/react-portal/test/specs/app.spec.js:7:1)
    at Module._compile (module.js:569:30)
    at loader (/Users/brianflannery/Development/react-portal/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/brianflannery/Development/react-portal/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at /Users/brianflannery/Development/react-portal/node_modules/mocha/lib/mocha.js:230:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/brianflannery/Development/react-portal/node_modules/mocha/lib/mocha.js:227:14)
    at Mocha.run (/Users/brianflannery/Development/react-portal/node_modules/mocha/lib/mocha.js:495:10)
    at Object.<anonymous> (/Users/brianflannery/Development/react-portal/node_modules/mocha/bin/_mocha:460:18)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3`

**Comment by n1arash** [comment]
+1

**Comment by ardcore** [comment]
I'm also seeing this error. Any progress?

**Comment by ardcore** [comment]
we managed to solve this by adding `jest.mock("react-ga")`

**Comment by SimeonC** [comment]
Ah, forgot to tag this issue. The latest release has a ["test mode" (README)](https://github.com/react-ga/react-ga#test-mode) that should allow you to test your React-GA code is running properly.

**Comment by MarcoNicolodi** [comment]
I think the issue is that ReactGA is trying to acess window/document properties from a node environment, so this test mode wouldnt solve this. 
I have 3 tests that import the file in which `React.GA` is initialized, and since `jest`run in a node environment, trying to access the `parentNode` property of a DOM element throws an error, failing the tests.

**Comment by SimeonC** [comment]
No, testMode is designed for usage in node. See this REPL that’s all running in node https://runkit.com/simeonc/5ab4f87d90b3840013600465

**Comment by MarcoNicolodi** [comment]
I used it today and it solved our problem. Thank you.

**Comment by akougblenou** [comment]
@ardcore can you elaborate on your fix ? did you setup the mock globally (for instance in a mock file load at setup) or was it done in another way ?

**Comment by withoutwax** [comment]
I was able to solve by adding `{ testMode: true }` to `.initialize()` function as the [React-ga](https://github.com/react-ga/react-ga#test-mode) documentation suggests:

```JavaScript
ReactGoogleAnalytics.initialize("UA-0000000-0", { testMode: true });
```

**Comment by thomazmz** [comment]
@SimeonC would it be necessary to pass `{ testMode: true }` as a seccond argument if we use `jest.mock("react-ga")`?

**Comment by SimeonC** [comment]
It depends on how your using the jest mock. The auto mock still calls the file and contents I think. If you do a full mock so that the react fast code isn’t called you shouldn’t need the testMode. Probably you could mock out just the init function to prevent GA from loading and just create window.ga for your tests in the mock. That option was added back when mocha had terrible painful mocking and doing this was just plain easier, also if you wanted to run “manual testing” by just clicking around the app and checking what calls are made.
